### PR TITLE
TU-95 FDM rework

### PR DESCRIPTION
**Pull request by IAHM-COL**
- N-22 has kindly revised the TU-95 FDM (both a yasim and a jsbsim version) using sources from the dc6 and the TU-14
- http://forum.flightgear.org/viewtopic.php?f=4&t=25643

### CODE REVIEW

**Comment by IAHM-COL** [comment]
@helijah 
Hi Helijah

These are the changes that N22 made on the Bear to improve the FDM and flyability

He is concerned of a "dissapearing gear" after he made these changes :-1: 

I created this merge request from a fork I made on my account for beign able to be validated and revised by you.

Thanks
Israel

**Comment by helijah** [comment]
Hi N22, Israel

The N22 mail arrived this morning at home :)
I'll watch this loan and do the necessary :)

Regards Emmanuel

**Comment by IAHM-COL** [comment]
Thanks Emmanuel

I received your email notification about these suggestions. 
As replied by email, I isolated this proposal in an experimental branch, I named N22, but it does not affect the current master branch in any sense. 

Please let me know if you have questions, 
Best regard, 
Israel

**Comment by helijah** [comment]
Hey Israel,

Ok :) And sorry for my error :) On the K7 it's Edward not N22

So I started the important updates for these two models (95 and Tu K-7)

Today (Thursday) tomorrow and after tomorrow, I'm at work, but Sunday,  I finish updates and puts it all online.

Regards Emmanuel

----- Mail original -----
De: "Israel Hernandez" notifications@github.com
À: "FGMEMBERS/TU-95" TU-95@noreply.github.com
Cc: "BARANGER Emmanuel" embaranger@free.fr
Envoyé: Mercredi 18 Mars 2015 16:10:43
Objet: Re: [TU-95] TU-95 FDM rework (#1)

Thanks Emmanuel 

I received your email notification about these suggestions. 
As replied by email, I isolated this proposal in an experimental branch, I named N22, but it does not affect the current master branch in any sense. 

Please let me know if you have questions, 
Best regard, 
Israel

**Comment by FGDATA** [comment]
Very Appreciated, Helijah

Best,
Israel

On Thu, Mar 19, 2015 at 4:50 PM, BARANGER Emmanuel <notifications@github.com

**Pull request closed without merging**
